# golangci-lint configuration for golangci-lint v2.5+
# https://golangci-lint.run/usage/configuration/
# Both CI and local development use v2.5.0 for consistency
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  settings:
    gocyclo:
      min-complexity: 21  # Allow up to 20 (for NewColumnCollections and FilterModels)
    
    goconst:
      min-len: 3
      min-occurrences: 3
  default: none
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    
    # Additional linters  
    - goconst       # Find repeated strings
    - gocyclo       # Check cyclomatic complexity
    - misspell      # Check for misspelled words
  
  disable:
    - unused        # Some functions kept for future features
    - gosec         # File operations are expected in CLI tools
    - dupl          # Some repetition is acceptable for clarity

formatters:
  enable:
    - gofmt         # Check and fix formatting
    - goimports     # Check and fix imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0


