# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    
    # Additional linters  
    - goconst       # Find repeated strings
    - gocyclo       # Check cyclomatic complexity
    - misspell      # Check for misspelled words
    # Note: gosec disabled - file operations are expected in CLI tools
    # Note: dupl disabled - some repetition is acceptable for clarity

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-dirs:
    - tests/fixtures
  
  exclude-files:
    - ".*\\.pb\\.go$"
  
  exclude-rules:
    # Exclude unused code warnings - some code is kept for future features
    - linters:
        - unused
      text: "is unused"
    
    # Allow high complexity in specific functions
    - linters:
        - gocyclo
      text: "NewColumnCollections|FilterModels"
  
  max-issues-per-linter: 0
  max-same-issues: 0
